/**
 * Trigger claims: a plugin that generates triggers (the Trigger Script plugin builds a
 * block of them from its source) tells the editor which run of the list is its, and the
 * editor's own trigger editors show those rows badged and locked, with a way to the
 * plugin's editor, instead of letting the user edit records the next build will replace.
 *
 * A claim finds its run by *content* (`spec.locate(list)`) rather than by remembered
 * index, because the Classic editor works on a working copy with local inserts and
 * removals in it — the run has to be found again in whatever list an editor holds.
 * Everything here is pure; the entries live in `pluginTriggerClaimsAtom`.
 */
import type { TriggerRecord } from "../formats/chk/sections/triggers";
import type { PluginTriggerClaim } from "../atoms/pluginAtoms";

/** One claim as located in one list. */
export interface ClaimedRange {
  claim: PluginTriggerClaim;
  start: number;
  count: number;
}

/** Every claim that finds its run in `list`, first run first; a `locate` that throws is skipped. */
export function locateClaims(claims: readonly PluginTriggerClaim[], list: TriggerRecord[]): ClaimedRange[] {
  const out: ClaimedRange[] = [];
  for (const claim of claims) {
    let where: { start: number; count: number } | null = null;
    try {
      where = claim.spec.locate(list);
    } catch (err) {
      console.error(`[${claim.pluginName}] trigger claim failed to locate its run`, err);
    }
    if (!where) continue;
    const start = Math.max(0, Math.min(list.length, Math.floor(where.start)));
    const count = Math.max(0, Math.min(list.length - start, Math.floor(where.count)));
    out.push({ claim, start, count });
  }
  return out.sort((a, b) => a.start - b.start);
}

/** The range a trigger index falls in, if any. */
export function claimAt(ranges: readonly ClaimedRange[], index: number): ClaimedRange | null {
  return ranges.find((r) => index >= r.start && index < r.start + r.count) ?? null;
}

/** The badge word a claimed row shows. */
export function claimBadge(range: ClaimedRange): string {
  return range.claim.spec.badge?.trim() || range.claim.pluginId;
}

/** What the editor says in place of a locked trigger's form. */
export function claimDescription(range: ClaimedRange, index: number, list: TriggerRecord[]): string {
  try {
    const text = range.claim.spec.describe?.(index, list);
    if (text) return text;
  } catch (err) {
    console.error(`[${range.claim.pluginName}] trigger claim failed to describe a trigger`, err);
  }
  return `This trigger is generated by ${range.claim.spec.label}. Edit it there; a rebuild replaces the whole run.`;
}
