# Generated by npm run docs:reference from the scmJS CHK format reference. Do not edit.
meta:
  id: starcraft_scenario_chk
  title: "StarCraft and Brood War scenario file (scenario.chk)"
  application:
    - StarCraft
    - "StarCraft: Brood War"
    - "StarCraft: Remastered"
  file-extension: chk
  license: MIT
  ks-version: "0.10"
  endian: le
doc: |
  The scenario inside a StarCraft map archive (.scm, .scx): a run of sections, each a
  four-character name, a 32-bit length and that many bytes.

  Generated from the scmJS CHK format reference, which explains every field:
  https://docs.scmjs.dev/chk/

  This reads a file section by section and keeps repeats. It does not combine repeated
  sections the way the game does, and a negative length or one past the end of the file
  stops it; protected maps use both. Sizes that follow from DIM (MTXM, TILE, MASK, ISOM)
  are read to the end of the section.
doc-ref: "https://docs.scmjs.dev/chk/"
seq:
  - id: sections
    type: section
    repeat: eos
types:
  section:
    seq:
      - id: name
        type: str
        size: 4
        encoding: "ISO-8859-1"
        doc: "Padded with spaces: \"VER \", \"DIM \", \"STR \"."
      - id: length
        type: s4
      - id: body
        size: length
        type:
          switch-on: name
          cases:
            "\"TYPE\"": sec_type
            "\"VER \"": sec_ver
            "\"IVER\"": sec_iver
            "\"IVE2\"": sec_ive2
            "\"VCOD\"": sec_vcod
            "\"IOWN\"": sec_iown
            "\"OWNR\"": sec_ownr
            "\"ERA \"": sec_era
            "\"DIM \"": sec_dim
            "\"SIDE\"": sec_side
            "\"MTXM\"": sec_mtxm
            "\"PUNI\"": sec_puni
            "\"UPGR\"": sec_upgr
            "\"PTEC\"": sec_ptec
            "\"UNIT\"": sec_unit
            "\"ISOM\"": sec_isom
            "\"TILE\"": sec_tile
            "\"DD2 \"": sec_dd2
            "\"THG2\"": sec_thg2
            "\"MASK\"": sec_mask
            "\"STR \"": sec_str
            "\"UPRP\"": sec_uprp
            "\"UPUS\"": sec_upus
            "\"MRGN\"": sec_mrgn
            "\"TRIG\"": sec_trig
            "\"MBRF\"": sec_mbrf
            "\"SPRP\"": sec_sprp
            "\"FORC\"": sec_forc
            "\"WAV \"": sec_wav
            "\"UNIS\"": sec_unis
            "\"UPGS\"": sec_upgs
            "\"TECS\"": sec_tecs
            "\"SWNM\"": sec_swnm
            "\"COLR\"": sec_colr
            "\"PUPx\"": sec_pupx
            "\"PTEx\"": sec_ptex
            "\"UNIx\"": sec_unix
            "\"UPGx\"": sec_upgx
            "\"TECx\"": sec_tecx
            "\"STRx\"": sec_strx
            "\"CRGB\"": sec_crgb
  tile:
    doc: "A tile number: the tileset's CV5 tile group and the megatile within it."
    seq:
      - id: raw
        type: u2
    instances:
      group:
        value: "raw >> 4"
        doc: "The tile group in the tileset's CV5."
      variation:
        value: "raw & 0xf"
        doc: "Which of the group's 16 megatiles."
  string_at:
    params:
      - id: ofs
        type: u4
    instances:
      text:
        pos: ofs
        io: "_parent._io"
        terminator: 0
        eos-error: false
        if: "ofs < _parent._io.size"
        doc: "The string's bytes. The file does not say which encoding they are in."
  sec_type:
    doc-ref: "https://docs.scmjs.dev/chk/type/"
    seq:
      - id: game
        type: str
        size: 4
        encoding: ASCII
        doc: "RAWS for a StarCraft file, RAWB for Brood War"
    doc: "TYPE: read by the game."
  sec_ver:
    doc-ref: "https://docs.scmjs.dev/chk/ver/"
    seq:
      - id: revision
        type: u2
        doc: "The revision; see Revisions"
    doc: "VER: read by the game."
  sec_iver:
    doc-ref: "https://docs.scmjs.dev/chk/iver/"
    seq:
      - id: version
        type: u2
        doc: "StarEdit's version number, an older form"
    doc: "IVER: read by editors only."
  sec_ive2:
    doc-ref: "https://docs.scmjs.dev/chk/ive2/"
    seq:
      - id: version
        type: u2
        doc: "StarEdit's version number; 11 in a map StarEdit saves for Brood War"
    doc: "IVE2: read by editors only."
  sec_vcod:
    doc-ref: "https://docs.scmjs.dev/chk/vcod/"
    seq:
      - id: seeds
        type: u4
        repeat: expr
        repeat-expr: 256
        doc: Seeds
      - id: operations
        type: u1
        repeat: expr
        repeat-expr: 16
        doc: Operations
    doc: "VCOD: read by the game."
  sec_iown:
    doc-ref: "https://docs.scmjs.dev/chk/iown/"
    seq:
      - id: types
        type: u1
        repeat: expr
        repeat-expr: 12
        enum: player_type
        doc: "StarEdit's copy of each player's type, one byte per player slot, Player 1 first"
    doc: "IOWN: read by editors only."
  sec_ownr:
    doc-ref: "https://docs.scmjs.dev/chk/ownr/"
    seq:
      - id: types
        type: u1
        repeat: expr
        repeat-expr: 12
        enum: player_type
        doc: "Each player's type, one byte per player slot, Player 1 first"
    doc: "OWNR: read by the game."
  sec_era:
    doc-ref: "https://docs.scmjs.dev/chk/era/"
    seq:
      - id: tileset
        type: u2
        enum: tileset
        doc: "The tileset. The game uses the low three bits"
    doc: "ERA: read by the game."
  sec_dim:
    doc-ref: "https://docs.scmjs.dev/chk/dim/"
    seq:
      - id: width
        type: u2
        doc: "Width in tiles"
      - id: height
        type: u2
        doc: "Height in tiles"
    doc: "DIM: read by the game."
  sec_side:
    doc-ref: "https://docs.scmjs.dev/chk/side/"
    seq:
      - id: races
        type: u1
        repeat: expr
        repeat-expr: 12
        enum: race
        doc: "Each player's race, one byte per player slot, Player 1 first"
    doc: "SIDE: read by the game."
  sec_mtxm:
    doc-ref: "https://docs.scmjs.dev/chk/mtxm/"
    seq:
      - id: tiles
        type: tile
        repeat: eos
        doc: "The tile shown at each position, row by row from the top left: the tile group × 16 + the tile's place in the group"
    doc: "MTXM: read by the game."
  sec_puni:
    doc-ref: "https://docs.scmjs.dev/chk/puni/"
    seq:
      - id: available
        type: u1
        repeat: expr
        repeat-expr: 2736
        doc: "Per player, per unit type: 1 if the player can build it. Player 1's 228 bytes first"
      - id: default_available
        type: u1
        repeat: expr
        repeat-expr: 228
        doc: "Per unit type: 1 if it can be built, for every player that uses the default"
      - id: uses_default
        type: u1
        repeat: expr
        repeat-expr: 2736
        doc: "Per player, per unit type: 1 if the player uses the default"
    doc: "PUNI: read by the game."
  sec_upgr:
    doc-ref: "https://docs.scmjs.dev/chk/upgr/"
    seq:
      - id: max_levels
        type: u1
        repeat: expr
        repeat-expr: 552
        doc: "Per player, per upgrade: the highest level they may research. Player 1's 46 bytes first"
      - id: start_levels
        type: u1
        repeat: expr
        repeat-expr: 552
        doc: "Per player, per upgrade: the level they start at"
      - id: default_max_levels
        type: u1
        repeat: expr
        repeat-expr: 46
        doc: "Per upgrade: the default highest level"
      - id: default_start_levels
        type: u1
        repeat: expr
        repeat-expr: 46
        doc: "Per upgrade: the default starting level"
      - id: uses_default
        type: u1
        repeat: expr
        repeat-expr: 552
        doc: "Per player, per upgrade: 1 if the player uses the defaults"
    doc: "UPGR: read by the game."
  sec_ptec:
    doc-ref: "https://docs.scmjs.dev/chk/ptec/"
    seq:
      - id: available
        type: u1
        repeat: expr
        repeat-expr: 288
        doc: "Per player, per ability: 1 if they may research it. Player 1's 24 bytes first"
      - id: researched
        type: u1
        repeat: expr
        repeat-expr: 288
        doc: "Per player, per ability: 1 if they start with it"
      - id: default_available
        type: u1
        repeat: expr
        repeat-expr: 24
        doc: "Per ability: the default for may research"
      - id: default_researched
        type: u1
        repeat: expr
        repeat-expr: 24
        doc: "Per ability: the default for start with"
      - id: uses_default
        type: u1
        repeat: expr
        repeat-expr: 288
        doc: "Per player, per ability: 1 if the player uses the defaults"
    doc: "PTEC: read by the game."
  sec_unit:
    doc-ref: "https://docs.scmjs.dev/chk/unit/"
    seq:
      - id: units
        type: unit
        repeat: eos
    doc: "UNIT: read by the game."
  sec_isom:
    doc-ref: "https://docs.scmjs.dev/chk/isom/"
    seq:
      - id: rects
        type: isom_rect
        repeat: eos
        doc: "(width / 2 + 1) × (height + 1) rects, row by row."
    doc: "ISOM: read by editors only."
  sec_tile:
    doc-ref: "https://docs.scmjs.dev/chk/tile/"
    seq:
      - id: tiles
        type: tile
        repeat: eos
        doc: "The tile at each position with the doodads left out, row by row from the top left"
    doc: "TILE: read by editors only."
  sec_dd2:
    doc-ref: "https://docs.scmjs.dev/chk/dd2/"
    seq:
      - id: doodads
        type: doodad
        repeat: eos
    doc: "DD2: read by editors only."
  sec_thg2:
    doc-ref: "https://docs.scmjs.dev/chk/thg2/"
    seq:
      - id: sprites
        type: sprite
        repeat: eos
    doc: "THG2: read by the game."
  sec_mask:
    doc-ref: "https://docs.scmjs.dev/chk/mask/"
    seq:
      - id: tiles
        type: u1
        repeat: eos
        doc: "For each tile, one bit per player (bit 0 is Player 1): set where that player starts with the tile unexplored"
    doc: "MASK: read by the game."
  sec_str:
    doc-ref: "https://docs.scmjs.dev/chk/str/"
    seq:
      - id: count
        type: u2
      - id: offsets
        type: u2
        repeat: expr
        repeat-expr: count
        doc: "Where each string starts, from the start of the section. String numbers count from 1: offsets[0] is string 1."
    instances:
      strings:
        type: "string_at(offsets[_index])"
        repeat: expr
        repeat-expr: count
        doc: "strings[0] is string 1."
    doc: "STR: read by the game."
  sec_uprp:
    doc-ref: "https://docs.scmjs.dev/chk/uprp/"
    seq:
      - id: properties_slots
        type: properties_slot
        repeat: expr
        repeat-expr: 64
    doc: "UPRP: read by the game."
  sec_upus:
    doc-ref: "https://docs.scmjs.dev/chk/upus/"
    seq:
      - id: in_use
        type: u1
        repeat: expr
        repeat-expr: 64
        doc: "Per slot: 1 if StarEdit considers it in use"
    doc: "UPUS: read by editors only."
  sec_mrgn:
    doc-ref: "https://docs.scmjs.dev/chk/mrgn/"
    seq:
      - id: locations
        type: location
        repeat: eos
    doc: "MRGN: read by the game."
  sec_trig:
    doc-ref: "https://docs.scmjs.dev/chk/trig/"
    seq:
      - id: triggers
        type: trigger
        repeat: eos
    doc: "TRIG: read by the game."
  sec_mbrf:
    doc-ref: "https://docs.scmjs.dev/chk/mbrf/"
    seq:
      - id: briefings
        type: briefing
        repeat: eos
    doc: "MBRF: read by the game."
  sec_sprp:
    doc-ref: "https://docs.scmjs.dev/chk/sprp/"
    seq:
      - id: name
        type: u2
        doc: "The scenario's name, a string number"
      - id: description
        type: u2
        doc: "Its description, a string number"
    doc: "SPRP: read by the game."
  sec_forc:
    doc-ref: "https://docs.scmjs.dev/chk/forc/"
    seq:
      - id: player_forces
        type: u1
        repeat: expr
        repeat-expr: 8
        doc: "The force of each of Players 1 to 8, 0 to 3"
      - id: force_names
        type: u2
        repeat: expr
        repeat-expr: 4
        doc: "The name of each force, a string number"
      - id: force_flags
        type: u1
        repeat: expr
        repeat-expr: 4
        doc: "Each force's flags (below)"
    doc: "FORC: read by the game."
  sec_wav:
    doc-ref: "https://docs.scmjs.dev/chk/wav/"
    seq:
      - id: sound_names
        type: u4
        repeat: expr
        repeat-expr: 512
        doc: "The name of each sound, a string number; 0 for an empty slot"
    doc: "WAV: read by editors only."
  sec_unis:
    doc-ref: "https://docs.scmjs.dev/chk/unis/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 228
        doc: "Per unit type: 1 to use the game's own values and ignore the rest of this section"
      - id: hit_points
        type: u4
        repeat: expr
        repeat-expr: 228
        doc: "Hit points × 256"
      - id: shields
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: Shields
      - id: armor
        type: u1
        repeat: expr
        repeat-expr: 228
        doc: Armour
      - id: build_time
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Build time, in game frames"
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Mineral cost"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Gas cost"
      - id: name_index
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Name, a string number; 0 for the default name"
      - id: weapon_damage
        type: u2
        repeat: expr
        repeat-expr: 100
        doc: "Per weapon: base damage"
      - id: weapon_bonus
        type: u2
        repeat: expr
        repeat-expr: 100
        doc: "Per weapon: damage added by each upgrade level"
    doc: "UNIS: read by the game."
  sec_upgs:
    doc-ref: "https://docs.scmjs.dev/chk/upgs/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 46
        doc: "Per upgrade: 1 to use the game's own values"
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Mineral cost of the first level"
      - id: mineral_factor
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Minerals added for each further level"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Gas cost of the first level"
      - id: gas_factor
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Gas added for each further level"
      - id: time_cost
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Research time of the first level, in game frames"
      - id: time_factor
        type: u2
        repeat: expr
        repeat-expr: 46
        doc: "Time added for each further level"
    doc: "UPGS: read by the game."
  sec_tecs:
    doc-ref: "https://docs.scmjs.dev/chk/tecs/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 24
        doc: "Per ability: 1 to use the game's own values"
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 24
        doc: "Mineral cost"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 24
        doc: "Gas cost"
      - id: research_time
        type: u2
        repeat: expr
        repeat-expr: 24
        doc: "Research time, in game frames"
      - id: energy_cost
        type: u2
        repeat: expr
        repeat-expr: 24
        doc: "Energy cost"
    doc: "TECS: read by the game."
  sec_swnm:
    doc-ref: "https://docs.scmjs.dev/chk/swnm/"
    seq:
      - id: switch_names
        type: u4
        repeat: expr
        repeat-expr: 256
        doc: "The name of each switch, a string number; 0 for none"
    doc: "SWNM: read by editors only."
  sec_colr:
    doc-ref: "https://docs.scmjs.dev/chk/colr/"
    seq:
      - id: colors
        type: u1
        repeat: expr
        repeat-expr: 8
        enum: color
        doc: "The colour of each of Players 1 to 8"
    doc: "COLR: read by the game."
  sec_pupx:
    doc-ref: "https://docs.scmjs.dev/chk/pupx/"
    seq:
      - id: max_levels
        type: u1
        repeat: expr
        repeat-expr: 732
        doc: "Per player, per upgrade: the highest level they may research. Player 1's 61 bytes first"
      - id: start_levels
        type: u1
        repeat: expr
        repeat-expr: 732
        doc: "Per player, per upgrade: the level they start at"
      - id: default_max_levels
        type: u1
        repeat: expr
        repeat-expr: 61
        doc: "Per upgrade: the default highest level"
      - id: default_start_levels
        type: u1
        repeat: expr
        repeat-expr: 61
        doc: "Per upgrade: the default starting level"
      - id: uses_default
        type: u1
        repeat: expr
        repeat-expr: 732
        doc: "Per player, per upgrade: 1 if the player uses the defaults"
    doc: "PUPx: read by the game."
  sec_ptex:
    doc-ref: "https://docs.scmjs.dev/chk/ptex/"
    seq:
      - id: available
        type: u1
        repeat: expr
        repeat-expr: 528
        doc: "Per player, per ability: 1 if they may research it. Player 1's 44 bytes first"
      - id: researched
        type: u1
        repeat: expr
        repeat-expr: 528
        doc: "Per player, per ability: 1 if they start with it"
      - id: default_available
        type: u1
        repeat: expr
        repeat-expr: 44
        doc: "Per ability: the default for may research"
      - id: default_researched
        type: u1
        repeat: expr
        repeat-expr: 44
        doc: "Per ability: the default for start with"
      - id: uses_default
        type: u1
        repeat: expr
        repeat-expr: 528
        doc: "Per player, per ability: 1 if the player uses the defaults"
    doc: "PTEx: read by the game."
  sec_unix:
    doc-ref: "https://docs.scmjs.dev/chk/unix/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 228
        doc: "Per unit type: 1 to use the game's own values and ignore the rest of this section"
      - id: hit_points
        type: u4
        repeat: expr
        repeat-expr: 228
        doc: "Hit points × 256"
      - id: shields
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: Shields
      - id: armor
        type: u1
        repeat: expr
        repeat-expr: 228
        doc: Armour
      - id: build_time
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Build time, in game frames"
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Mineral cost"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Gas cost"
      - id: name_index
        type: u2
        repeat: expr
        repeat-expr: 228
        doc: "Name, a string number; 0 for the default name"
      - id: weapon_damage
        type: u2
        repeat: expr
        repeat-expr: 130
        doc: "Per weapon: base damage"
      - id: weapon_bonus
        type: u2
        repeat: expr
        repeat-expr: 130
        doc: "Per weapon: damage added by each upgrade level"
    doc: "UNIx: read by the game."
  sec_upgx:
    doc-ref: "https://docs.scmjs.dev/chk/upgx/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 61
        doc: "Per upgrade: 1 to use the game's own values"
      - id: unused
        type: u1
        doc: Unused
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Mineral cost of the first level"
      - id: mineral_factor
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Minerals added for each further level"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Gas cost of the first level"
      - id: gas_factor
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Gas added for each further level"
      - id: time_cost
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Research time of the first level, in game frames"
      - id: time_factor
        type: u2
        repeat: expr
        repeat-expr: 61
        doc: "Time added for each further level"
    doc: "UPGx: read by the game."
  sec_tecx:
    doc-ref: "https://docs.scmjs.dev/chk/tecx/"
    seq:
      - id: use_default
        type: u1
        repeat: expr
        repeat-expr: 44
        doc: "Per ability: 1 to use the game's own values"
      - id: mineral_cost
        type: u2
        repeat: expr
        repeat-expr: 44
        doc: "Mineral cost"
      - id: gas_cost
        type: u2
        repeat: expr
        repeat-expr: 44
        doc: "Gas cost"
      - id: research_time
        type: u2
        repeat: expr
        repeat-expr: 44
        doc: "Research time, in game frames"
      - id: energy_cost
        type: u2
        repeat: expr
        repeat-expr: 44
        doc: "Energy cost"
    doc: "TECx: read by the game."
  sec_strx:
    doc-ref: "https://docs.scmjs.dev/chk/strx/"
    seq:
      - id: count
        type: u4
      - id: offsets
        type: u4
        repeat: expr
        repeat-expr: count
        doc: "Where each string starts, from the start of the section. String numbers count from 1: offsets[0] is string 1."
    instances:
      strings:
        type: "string_at(offsets[_index])"
        repeat: expr
        repeat-expr: count
        doc: "strings[0] is string 1."
    doc: "STRx: read by the game."
  sec_crgb:
    doc-ref: "https://docs.scmjs.dev/chk/crgb/"
    seq:
      - id: rgb
        type: u1
        repeat: expr
        repeat-expr: 24
        doc: "Red, green and blue for each of Players 1 to 8, three bytes each"
      - id: modes
        type: u1
        repeat: expr
        repeat-expr: 8
        doc: "How each player's colour is chosen (modes, below)"
        enum: color_mode
    doc: "CRGB: read by the game."
  unit:
    seq:
      - id: serial
        type: u4
        doc: "The unit's serial number, unique in the map; add-ons and nydus canals are linked by it"
      - id: x
        type: u2
        doc: "X position in pixels"
      - id: y
        type: u2
        doc: "Y position in pixels"
      - id: unit_id
        type: u2
        doc: "Unit type"
      - id: relation_type
        type: u2
        doc: "How the unit is linked to another (relations, below)"
      - id: valid_properties
        type: u2
        doc: "Which special states the record sets (below)"
      - id: valid_states
        type: u2
        doc: "Which of the following fields the record sets (fields set, below)"
      - id: owner
        type: u1
        doc: "Owner, 0 for Player 1"
      - id: hit_points_percent
        type: u1
        doc: "Hit points, per cent of the maximum"
      - id: shield_percent
        type: u1
        doc: "Shields, per cent"
      - id: energy_percent
        type: u1
        doc: "Energy, per cent"
      - id: resource_amount
        type: u4
        doc: "Resources, for a mineral field or geyser"
      - id: hangar_units
        type: u2
        doc: "Units in the hangar: interceptors or scarabs"
      - id: state_flags
        type: u2
        doc: "The special states themselves"
      - id: unused
        type: u4
        doc: Unused
      - id: related_serial
        type: u4
        doc: "Serial number of the linked unit"
    instances:
      relation_type_nydus_link:
        value: "(relation_type & 0x200) != 0"
      relation_type_addon:
        value: "(relation_type & 0x400) != 0"
      state_flags_cloaked:
        value: "(state_flags & 0x1) != 0"
      state_flags_burrowed:
        value: "(state_flags & 0x2) != 0"
      state_flags_in_transit:
        value: "(state_flags & 0x4) != 0"
      state_flags_hallucinated:
        value: "(state_flags & 0x8) != 0"
      state_flags_invincible:
        value: "(state_flags & 0x10) != 0"
      valid_states_owner:
        value: "(valid_states & 0x1) != 0"
      valid_states_hit_points:
        value: "(valid_states & 0x2) != 0"
      valid_states_shields:
        value: "(valid_states & 0x4) != 0"
      valid_states_energy:
        value: "(valid_states & 0x8) != 0"
      valid_states_resources:
        value: "(valid_states & 0x10) != 0"
      valid_states_hangar:
        value: "(valid_states & 0x20) != 0"
      valid_states_state:
        value: "(valid_states & 0x40) != 0"
  isom_rect:
    doc: "A rect two tiles wide and one tall; each word is a quarter of one of the two diamonds the rect's diagonal divides it between."
    seq:
      - id: left
        type: isom_word
        doc: "The word on the rect's left side"
      - id: top
        type: isom_word
        doc: "Its top side"
      - id: right
        type: isom_word
        doc: "Its right side"
      - id: bottom
        type: isom_word
        doc: "Its bottom side"
  isom_word:
    seq:
      - id: raw
        type: u2
    instances:
      value:
        value: "raw >> 4"
        doc: "The diamond's value: a flat terrain, or an edge set's first value plus its shape (0 to 13)."
      quarter:
        value: "(raw >> 2) & 3"
        enum: isom_quarter
        doc: "Which quarter of its diamond the word is. StarEdit leaves these bits 0 on ground it filled rather than painted."
      second_side:
        value: "((raw >> 1) & 1) != 0"
        doc: "Which of the quarter's two rect sides this word is."
  doodad:
    seq:
      - id: doodad_id
        type: u2
        doc: "Doodad number in the tileset's list of doodads"
      - id: x
        type: u2
        doc: "X of the middle of the doodad, in pixels"
      - id: y
        type: u2
        doc: "Y of the middle of the doodad, in pixels"
      - id: owner
        type: u1
        doc: Owner
      - id: disabled
        type: u1
        doc: "1 if disabled, else 0"
  sprite:
    seq:
      - id: sprite_id
        type: u2
        doc: "Sprite number, or the unit type for a unit sprite (see the flags)"
      - id: x
        type: u2
        doc: "X in pixels"
      - id: y
        type: u2
        doc: "Y in pixels"
      - id: owner
        type: u1
        doc: Owner
      - id: unused
        type: u1
        doc: Unused
      - id: flags
        type: u2
        doc: "Flags (below)"
    instances:
      flags_pure_sprite:
        value: "(flags & 0x1000) != 0"
      flags_flipped:
        value: "(flags & 0x4000) != 0"
      flags_disabled:
        value: "(flags & 0x8000) != 0"
  properties_slot:
    seq:
      - id: valid_properties
        type: u2
        doc: "Which special states the slot sets (below)"
      - id: valid_fields
        type: u2
        doc: "Which fields the slot sets (below)"
      - id: owner
        type: u1
        doc: "Owner; unused"
      - id: hit_points_percent
        type: u1
        doc: "Hit points, per cent"
      - id: shields_percent
        type: u1
        doc: "Shields, per cent"
      - id: energy_percent
        type: u1
        doc: "Energy, per cent"
      - id: resources
        type: u4
        doc: Resources
      - id: hangar
        type: u2
        doc: "Units in the hangar"
      - id: state_flags
        type: u2
        doc: "The special states themselves"
      - id: unused
        type: u4
        doc: Unused
    instances:
      state_flags_cloaked:
        value: "(state_flags & 0x1) != 0"
      state_flags_burrowed:
        value: "(state_flags & 0x2) != 0"
      state_flags_in_transit:
        value: "(state_flags & 0x4) != 0"
      state_flags_hallucinated:
        value: "(state_flags & 0x8) != 0"
      state_flags_invincible:
        value: "(state_flags & 0x10) != 0"
      valid_fields_owner:
        value: "(valid_fields & 0x1) != 0"
      valid_fields_hit_points:
        value: "(valid_fields & 0x2) != 0"
      valid_fields_shields:
        value: "(valid_fields & 0x4) != 0"
      valid_fields_energy:
        value: "(valid_fields & 0x8) != 0"
      valid_fields_resources:
        value: "(valid_fields & 0x10) != 0"
      valid_fields_hangar:
        value: "(valid_fields & 0x20) != 0"
  location:
    seq:
      - id: left
        type: s4
        doc: "Left edge, in pixels"
      - id: top
        type: s4
        doc: "Top edge"
      - id: right
        type: s4
        doc: "Right edge"
      - id: bottom
        type: s4
        doc: "Bottom edge"
      - id: name_index
        type: u2
        doc: "Name, a string number"
      - id: elevation_flags
        type: u2
        doc: "Elevations the location leaves out (below)"
    instances:
      elevation_flags_low_ground:
        value: "(elevation_flags & 0x1) != 0"
      elevation_flags_medium_ground:
        value: "(elevation_flags & 0x2) != 0"
      elevation_flags_high_ground:
        value: "(elevation_flags & 0x4) != 0"
      elevation_flags_low_air:
        value: "(elevation_flags & 0x8) != 0"
      elevation_flags_medium_air:
        value: "(elevation_flags & 0x10) != 0"
      elevation_flags_high_air:
        value: "(elevation_flags & 0x20) != 0"
  trigger:
    doc: "One trigger, 2400 bytes."
    seq:
      - id: conditions
        type: condition
        repeat: expr
        repeat-expr: 16
        doc: "The list ends at the first slot whose type is 0."
      - id: actions
        type: action
        repeat: expr
        repeat-expr: 64
        doc: "The list ends at the first slot whose type is 0."
      - id: flags
        type: u4
        doc: "0x04 preserved, 0x08 disabled, 0x02 ignores Defeat and Draw; the rest are the game's while it runs."
      - id: players
        type: u1
        repeat: expr
        repeat-expr: 27
        doc: "Per player or group: non-zero where the trigger runs for it."
      - id: current_action
        type: u1
        doc: "Used by the game while the trigger runs; 0 in a saved map."
  briefing:
    doc: "One mission briefing, in the trigger's record with its own actions."
    seq:
      - id: conditions
        type: condition
        repeat: expr
        repeat-expr: 16
        doc: "The list ends at the first slot whose type is 0."
      - id: actions
        type: briefing_action
        repeat: expr
        repeat-expr: 64
        doc: "The list ends at the first slot whose type is 0."
      - id: flags
        type: u4
        doc: "0x04 preserved, 0x08 disabled, 0x02 ignores Defeat and Draw; the rest are the game's while it runs."
      - id: players
        type: u1
        repeat: expr
        repeat-expr: 27
        doc: "Per player or group: non-zero where the trigger runs for it."
      - id: current_action
        type: u1
        doc: "Used by the game while the trigger runs; 0 in a saved map."
  condition:
    doc: "One condition, 20 bytes."
    seq:
      - id: location
        type: u4
        doc: "Location number, counted from 1; 0 for none."
      - id: player
        type: u4
        doc: "Player or group."
      - id: amount
        type: u4
        doc: "Amount compared against."
      - id: unit_id
        type: u2
        doc: "Unit type."
      - id: comparison
        type: u1
        doc: "Comparison, or the switch state for Switch."
      - id: condition_type
        type: u1
        enum: condition_type
        doc: "Which condition this is."
      - id: resource
        type: u1
        doc: "Resource type, score type or switch number, depending on the condition."
      - id: flags
        type: u1
        doc: "Flags: 0x02 disabled; the others are editor and game bookkeeping."
      - id: mask
        type: u2
        doc: "Unused by ordinary triggers; some EUD tools store a mask here."
  action:
    doc: "One action, 32 bytes."
    seq:
      - id: location
        type: u4
        doc: "Location number, counted from 1; 0 for none. The source location where there are two."
      - id: text
        type: u4
        doc: "String-table entry of the text."
      - id: wav
        type: u4
        doc: "String-table entry of the sound file's name."
      - id: time
        type: u4
        doc: "A time: milliseconds, or seconds for Set Countdown Timer."
      - id: player
        type: u4
        doc: "Player or group; the first player where there are two."
      - id: target
        type: u4
        doc: "Second player, destination location, amount, properties slot or AI script, depending on the action."
      - id: unit_id
        type: u2
        doc: "Unit type, or the score, resource or alliance type."
      - id: action_type
        type: u1
        enum: action_type
        doc: "Which action this is."
      - id: modifier
        type: u1
        doc: "Unit count, modifier, switch action, order or state, depending on the action."
      - id: flags
        type: u1
        doc: "Flags: 0x02 disabled, 0x04 always display; the others are editor and game bookkeeping."
      - id: padding
        type: u1
        doc: "Unused."
      - id: mask
        type: u2
        doc: "Unused by ordinary triggers; some EUD tools store a mask here."
  briefing_action:
    doc: "One briefing action, 32 bytes."
    seq:
      - id: location
        type: u4
        doc: "Location number, counted from 1; 0 for none. The source location where there are two."
      - id: text
        type: u4
        doc: "String-table entry of the text."
      - id: wav
        type: u4
        doc: "String-table entry of the sound file's name."
      - id: time
        type: u4
        doc: "A time: milliseconds, or seconds for Set Countdown Timer."
      - id: player
        type: u4
        doc: "Player or group; the first player where there are two."
      - id: target
        type: u4
        doc: "Second player, destination location, amount, properties slot or AI script, depending on the action."
      - id: unit_id
        type: u2
        doc: "Unit type, or the score, resource or alliance type."
      - id: action_type
        type: u1
        enum: briefing_action_type
        doc: "Which action this is."
      - id: modifier
        type: u1
        doc: "Unit count, modifier, switch action, order or state, depending on the action."
      - id: flags
        type: u1
        doc: "Flags: 0x02 disabled, 0x04 always display; the others are editor and game bookkeeping."
      - id: padding
        type: u1
        doc: "Unused."
      - id: mask
        type: u2
        doc: "Unused by ordinary triggers; some EUD tools store a mask here."
enums:
  player_type:
    0: inactive
    1: computer_game
    2: occupied
    3: rescuable
    4: computer_unused
    5: computer
    6: human
    7: neutral
    8: closed
    9: observer
  race:
    0: zerg
    1: terran
    2: protoss
    3: independent
    4: neutral
    5: user_selectable
    6: random
    7: inactive
  tileset:
    0: badlands
    1: space_platform
    2: installation
    3: ashworld
    4: jungle_world
    5: desert
    6: ice
    7: twilight
  color:
    0: red
    1: blue
    2: teal
    3: purple
    4: orange
    5: brown
    6: white
    7: yellow
    8: green
    9: pale_yellow
    10: tan
    11: dark_aqua
    12: pale_green
    13: bluish_grey
    14: pale_yellow_ii
    15: cyan
    16: pink
    17: olive
    18: lime
    19: navy
    20: dark_green
    21: black
  color_mode:
    0: random
    1: player_choice
    2: custom
    3: palette
  isom_quarter:
    0: top_left
    1: top_right
    2: bottom_right
    3: bottom_left
  condition_type:
    0: none
    1: countdown_timer
    2: command
    3: bring
    4: accumulate
    5: kill
    6: command_the_most
    7: command_the_most_at
    8: most_kills
    9: highest_score
    10: most_resources
    11: switch
    12: elapsed_time
    13: mission_briefing
    14: opponents
    15: deaths
    16: command_the_least
    17: command_the_least_at
    18: least_kills
    19: lowest_score
    20: least_resources
    21: score
    22: always
    23: never
  action_type:
    0: none
    1: victory
    2: defeat
    3: preserve_trigger
    4: wait
    5: pause_game
    6: unpause_game
    7: transmission
    8: play_wav
    9: display_text_message
    10: center_view
    11: create_unit_with_properties
    12: set_mission_objectives
    13: set_switch
    14: set_countdown_timer
    15: run_ai_script
    16: run_ai_script_at_location
    17: leader_board_control
    18: leader_board_control_at_location
    19: leader_board_resources
    20: leader_board_kills
    21: leader_board_points
    22: kill_unit
    23: kill_unit_at_location
    24: remove_unit
    25: remove_unit_at_location
    26: set_resources
    27: set_score
    28: minimap_ping
    29: talking_portrait
    30: mute_unit_speech
    31: unmute_unit_speech
    32: leaderboard_computer_players
    33: leaderboard_goal_control
    34: leaderboard_goal_control_at_location
    35: leaderboard_goal_resources
    36: leaderboard_goal_kills
    37: leaderboard_goal_points
    38: move_location
    39: move_unit
    40: leader_board_greed
    41: set_next_scenario
    42: set_doodad_state
    43: set_invincibility
    44: create_unit
    45: set_deaths
    46: order
    47: comment
    48: give_units_to_player
    49: modify_unit_hit_points
    50: modify_unit_energy
    51: modify_unit_shield_points
    52: modify_unit_resource_amount
    53: modify_unit_hanger_count
    54: pause_timer
    55: unpause_timer
    56: draw
    57: set_alliance_status
    58: disable_debug_mode
    59: enable_debug_mode
  briefing_action_type:
    0: none
    1: wait
    2: play_wav
    3: text_message
    4: mission_objectives
    5: show_portrait
    6: hide_portrait
    7: display_speaking_portrait
    8: transmission
    9: skip_tutorial_enabled
